scopping for: trap ERR
----
- set trap in one func
- trigger an error in another func
- will the error be trapped ?
